name: docker-compose CI

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker-compose
        run: |
          docker-compose build
          docker-compose up --detach
          docker-compose down
